### PR TITLE
Allow stable version of phpcs installer

### PR DESCRIPTION
**Pull request by fredden**
See https://github.com/PHPCSStandards/composer-installer/releases/tag/v1.0.0

### CODE REVIEW

**Comment by leonhelmus** [comment]
@fredden  Looks good to me!

**Review by igorwulff — APPROVED** [review]

**Comment by igorwulff** [comment]
@fredden @rutgerrademaker @leonhelmus can we get this merged? It has been open since 30 Jan and I did see a comment from Leon, but no approval.

**Comment by leonhelmus** [comment]
I approved this one already I think every commit it removes approvals.

**Review by leonhelmus — APPROVED** [review]

**Comment by leonhelmus** [comment]
@igorwulff can be merged now

**Pull request merged**
